### PR TITLE
Fix miyoo compilation name

### PR DESCRIPTION
**Pull request by phcoder**
@twinaphex

### CODE REVIEW

**Comment by jSTE0** [comment]
The `Makefile` doesn't actually build for Miyoo, I used this when testing:
```
diff --git a/Makefile b/Makefile
index 120971d..5e99531 100644
--- a/Makefile
+++ b/Makefile
@@ -216,6 +216,16 @@ else ifeq ($(platform), gcw0)
        DISABLE_ERROR_LOGGING := 1
        CFLAGS += -march=mips32 -mtune=mips32r2 -mhard-float
        LIBS = -lm
+
+# Miyoo
+else ifeq ($(platform), miyoo)
+   TARGET := $(TARGET_NAME)_libretro.so
+   CC = /opt/miyoo/usr/bin/arm-linux-gcc
+   AR = /opt/miyoo/usr/bin/arm-linux-ar
+   fpic := -fPIC
+   SHARED := -shared -Wl,-version-script=$(CORE_DIR)/link.T
+   CFLAGS += -ffast-math -mcpu=arm926ej-s
+
 # Windows MSVC 2010 x64
 else ifeq ($(platform), windows_msvc2010_x64)
        CC  = cl.exe
```
It's not really usable on Miyoo as the screen is only 320x240. Then again, this is also built for RS-90 which has an even lower resolution screen of 240x160.

**Comment by phcoder** [comment]
Why is resolution a problem? Mac II has resolution of 640 x 480 and 512 x 384. And frontend is able to downscale

**Comment by jSTE0** [comment]
When I tested, it was with an old HDD image I happened to have so I ended up on the System 7 desktop where icon labels, menus, etc. were unreadable after downscaling. Perhaps it will be fine with some games but I didn't have any handy to test with.
In any case, it still needs the `Makefile` changes, we could enable this core and leave it to others to test and suggest games and applications that would be suitable.

**Comment by phcoder** [comment]
Agreed for Makefile. Do you want to make the PR?

**Comment by jSTE0** [comment]
I think it'd be easier if you do it because this PR already exists, instead of two separate PRs.

**Comment by phcoder** [comment]
Done

> I think it'd be easier if you do it because this PR already exists, instead of two separate PRs.

Done

**Pull request merged**
